// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/link/link.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/link/link.go -destination=internal/service/link/mocks/link_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/edkin/url-shortener/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MocklinkRepository is a mock of linkRepository interface.
type MocklinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MocklinkRepositoryMockRecorder
	isgomock struct{}
}

// MocklinkRepositoryMockRecorder is the mock recorder for MocklinkRepository.
type MocklinkRepositoryMockRecorder struct {
	mock *MocklinkRepository
}

// NewMocklinkRepository creates a new mock instance.
func NewMocklinkRepository(ctrl *gomock.Controller) *MocklinkRepository {
	mock := &MocklinkRepository{ctrl: ctrl}
	mock.recorder = &MocklinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklinkRepository) EXPECT() *MocklinkRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocklinkRepository) Create(ctx context.Context, link models.Link) (models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, link)
	ret0, _ := ret[0].(models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MocklinkRepositoryMockRecorder) Create(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocklinkRepository)(nil).Create), ctx, link)
}

// GetByCode mocks base method.
func (m *MocklinkRepository) GetByCode(ctx context.Context, code string) (models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MocklinkRepositoryMockRecorder) GetByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MocklinkRepository)(nil).GetByCode), ctx, code)
}

// GetByURL mocks base method.
func (m *MocklinkRepository) GetByURL(ctx context.Context, url string) (models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByURL", ctx, url)
	ret0, _ := ret[0].(models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByURL indicates an expected call of GetByURL.
func (mr *MocklinkRepositoryMockRecorder) GetByURL(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByURL", reflect.TypeOf((*MocklinkRepository)(nil).GetByURL), ctx, url)
}

// MockcodeGenerator is a mock of codeGenerator interface.
type MockcodeGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockcodeGeneratorMockRecorder
	isgomock struct{}
}

// MockcodeGeneratorMockRecorder is the mock recorder for MockcodeGenerator.
type MockcodeGeneratorMockRecorder struct {
	mock *MockcodeGenerator
}

// NewMockcodeGenerator creates a new mock instance.
func NewMockcodeGenerator(ctrl *gomock.Controller) *MockcodeGenerator {
	mock := &MockcodeGenerator{ctrl: ctrl}
	mock.recorder = &MockcodeGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcodeGenerator) EXPECT() *MockcodeGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockcodeGenerator) Generate() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockcodeGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockcodeGenerator)(nil).Generate))
}

// Mockclock is a mock of clock interface.
type Mockclock struct {
	ctrl     *gomock.Controller
	recorder *MockclockMockRecorder
	isgomock struct{}
}

// MockclockMockRecorder is the mock recorder for Mockclock.
type MockclockMockRecorder struct {
	mock *Mockclock
}

// NewMockclock creates a new mock instance.
func NewMockclock(ctrl *gomock.Controller) *Mockclock {
	mock := &Mockclock{ctrl: ctrl}
	mock.recorder = &MockclockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclock) EXPECT() *MockclockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *Mockclock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockclockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*Mockclock)(nil).Now))
}

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockService) Resolve(ctx context.Context, code string) (models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, code)
	ret0, _ := ret[0].(models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockServiceMockRecorder) Resolve(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockService)(nil).Resolve), ctx, code)
}

// Shorten mocks base method.
func (m *MockService) Shorten(ctx context.Context, originalURL string) (models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", ctx, originalURL)
	ret0, _ := ret[0].(models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shorten indicates an expected call of Shorten.
func (mr *MockServiceMockRecorder) Shorten(ctx, originalURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MockService)(nil).Shorten), ctx, originalURL)
}
