// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (short_code, original_url, created_at)
VALUES ($1, $2, $3)
RETURNING short_code, original_url, created_at
`

type CreateLinkParams struct {
	ShortCode   string
	OriginalUrl string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.ShortCode, arg.OriginalUrl, arg.CreatedAt)
	var i Link
	err := row.Scan(&i.ShortCode, &i.OriginalUrl, &i.CreatedAt)
	return i, err
}

const createLinkIfNotExists = `-- name: CreateLinkIfNotExists :one
INSERT INTO links (short_code, original_url, created_at)
VALUES ($1, $2, $3)
ON CONFLICT (original_url) DO NOTHING
RETURNING short_code, original_url, created_at
`

type CreateLinkIfNotExistsParams struct {
	ShortCode   string
	OriginalUrl string
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateLinkIfNotExists(ctx context.Context, arg CreateLinkIfNotExistsParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLinkIfNotExists, arg.ShortCode, arg.OriginalUrl, arg.CreatedAt)
	var i Link
	err := row.Scan(&i.ShortCode, &i.OriginalUrl, &i.CreatedAt)
	return i, err
}

const getLinkByCode = `-- name: GetLinkByCode :one
SELECT short_code, original_url, created_at FROM links WHERE short_code = $1
`

func (q *Queries) GetLinkByCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByCode, shortCode)
	var i Link
	err := row.Scan(&i.ShortCode, &i.OriginalUrl, &i.CreatedAt)
	return i, err
}

const getLinkByURL = `-- name: GetLinkByURL :one
SELECT short_code, original_url, created_at FROM links WHERE original_url = $1
`

func (q *Queries) GetLinkByURL(ctx context.Context, originalUrl string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByURL, originalUrl)
	var i Link
	err := row.Scan(&i.ShortCode, &i.OriginalUrl, &i.CreatedAt)
	return i, err
}
