// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/link/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/link/handler.go -destination=internal/handler/link/mocks/handler_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/edkin/url-shortener/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MocklinkService is a mock of linkService interface.
type MocklinkService struct {
	ctrl     *gomock.Controller
	recorder *MocklinkServiceMockRecorder
	isgomock struct{}
}

// MocklinkServiceMockRecorder is the mock recorder for MocklinkService.
type MocklinkServiceMockRecorder struct {
	mock *MocklinkService
}

// NewMocklinkService creates a new mock instance.
func NewMocklinkService(ctrl *gomock.Controller) *MocklinkService {
	mock := &MocklinkService{ctrl: ctrl}
	mock.recorder = &MocklinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklinkService) EXPECT() *MocklinkServiceMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MocklinkService) Resolve(ctx context.Context, code string) (models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, code)
	ret0, _ := ret[0].(models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MocklinkServiceMockRecorder) Resolve(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MocklinkService)(nil).Resolve), ctx, code)
}

// Shorten mocks base method.
func (m *MocklinkService) Shorten(ctx context.Context, originalURL string) (models.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", ctx, originalURL)
	ret0, _ := ret[0].(models.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shorten indicates an expected call of Shorten.
func (mr *MocklinkServiceMockRecorder) Shorten(ctx, originalURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MocklinkService)(nil).Shorten), ctx, originalURL)
}
